### ISSUE TITLE
protobuf version

### ISSUE THREAD

**Issue by JohnhqWang** [xialeiliu/RankIQA#2]
Hi, thanks for the contribution to this repo. I am trying to reproduce the results but I got the following problem about the code. After searching around for a while, I think it is about the version of protobuf, the error messages are:

```
`layer {
  name: "accuracy"
  type: "Python"
  bottom: "fc8_m"
  bottom: "label"
  top: "loss"
  loss_weight: 1
  python_param {
    module: "src.MyLossLayer.netloss_live"
    layer: "MyLossLayer"
  }
}
I1203 18:47:56.705340 11601 layer_factory.hpp:77] Creating layer data
Traceback (most recent call last):
  File "/home/hq/RankIQA/src/data_layer/rank_layer_live.py", line 2, in <module>
    import caffe
  File "/home/hq/caffe-rc5/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/hq/caffe-rc5/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/hq/caffe-rc5/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/hq/caffe-rc5/python/caffe/proto/caffe_pb2.py", line 831, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'`
```

This issue is about the same question. https://github.com/BVLC/caffe/issues/6056. So I am wondering which version of protobuf are you using? Mine is 3.1.0.post1

```
`hq@ttx:~/RankIQA$ pip show protobuf
Name: protobuf
Version: 3.1.0.post1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: New BSD License
Location: /home/hq/.local/lib/python2.7/site-packages
Requires: six, setuptools
`
```
Thanks.

**Comment by xialeiliu** [comment]
Hi,
We have the same version of protobuf. From the error you reported, it seems that your pycaffe is not complied successfully, which should be easily checked in python or ipython environment.

**Comment by JohnhqWang** [comment]
Thanks. Let me check it first.
